pybo/views/main_view.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main',__name__,url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'hello, pybo!'

@bp.route('/')
def index():
    return redirect(url_for('shoes.main'))

pybo/views/model_views.py
from flask import Blueprint, url_for, request, render_template,flash
import os
from werkzeug.utils import redirect,secure_filename
from werkzeug.datastructures import CombinedMultiDict
from pybo.templates.modules.initclass import *
from .. import db
from pybo.models import Shoes,Shoesmodel,Structureprice
from ..forms import SearchShoes,ShoesModelCreateForm
from pybo.views.auth_views import login_required
from sqlalchemy import func,nullslast,select
import urllib
import urllib.request
import time

from multiprocessing import Process

bp = Blueprint('model',__name__,url_prefix='/model')


@bp.route('/list/<code>')
def _list(code):
    page = request.args.get('page', type=int, default=1)
    so = request.args.get('so',type=str, default='recent')
    code=code


    #정렬
    if so == 'expensive':
        model_list = Structureprice.query.filter(Structureprice.code.ilike(code)).order_by(Structureprice.price.desc())
    elif so =='popular':
        model_list = Structureprice.query.filter(Structureprice.code.ilike(code)).order_by(Structureprice.size.desc())
    else : #최신수
        model_list = Structureprice.query.filter(Structureprice.code.ilike(code)).order_by(Structureprice.saleday.desc())


    model_list = model_list.paginate(page, per_page=10)

    return render_template('shoes/amount_model.html', model_list=model_list,page=page,so=so,code=code)

@bp.route('/create/', methods=['GET', 'POST'])
def create():
    form = ShoesModelCreateForm()
    #form = ShoesModelCreateForm(CombinedMultiDict((request.files, request.form)))
    loading = url_for('static',filename='elephant.gif')

    if request.method == 'POST' and form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        brand = form.brand.data
        code = form.code.data
        color = form.colorway.data
        releasedate = form.releasedate.data
        uri=form.uri.data
        img = form.img.data

        rrrr = [name,price,brand,code,color,releasedate,img,uri]

        # 파일저장
        if img == None:
            filename = secure_filename(name)+'.jpg'
            img_path = os.path.join(
                os.getcwd(), r'pybo\static\crawling_data\model', filename)
            #urlretrieve(다운이미지경로,저장위치및이름)
            urllib.request.urlretrieve(uri, img_path)

        else:
            filename = secure_filename(img.filename)
            if name in filename :
                pass
            else:
                filename = secure_filename(name)+'.jpg'
            img.save(os.path.join(
                os.getcwd(), r'pybo\static\crawling_data\model', filename))

        model = Shoesmodel(code=code, img=filename, brand=brand,release_date=releasedate,name=name,colorway=color,retail_price=price)
        db.session.add(model)
        db.session.commit()
        howmany = process(code)

        flash(howmany)

        return redirect(url_for('model.view'))



    else:
        return render_template('shoes/shoes_model_create.html',form=form,loading=loading)




@bp.route('/view/')
def view():

    form = ShoesModelCreateForm()
    forms = form.brand.choices

    items = Shoesmodel.query.order_by(Shoesmodel.release_date.desc())
    return render_template('shoes/shoes_model_list.html',forms=forms,items=items)

def process(code):
    xxblue_total = []
    xb = Xxblue(code)
    xb.start()
    title,img_name = xb.search()
    tablenum = xb.element_generate()
    xb_obj = xb.parser()
    xb.driver.quit()


    # 모델 서브네임이없을 경우 추가한다.
    shoesmodel = Shoesmodel.query.filter(Shoesmodel.code ==code).first()
    if shoesmodel.subname == None:
        shoesmodel.subname = title

    num = 0
    # 중복값 비교
    comparison = Structureprice.query.filter(Structureprice.code.like(code)).order_by(Structureprice.id.desc()).first()

    if '없음' in xb_obj[0][0]:
        pass
    else:
        for i in xb_obj:

            size = i[0]
            price = int(i[1].replace(',', '').replace('원', ''))
            saleday = datetime.strptime(i[2], '%Y.%m.%d')
            # comparison 기존데이터 유무
            if comparison != None :
                if comparison.code == code and comparison.saleday ==saleday and comparison.price == price :
                    break
                else:
                    pass
            else : pass
            xxblue_total.insert(0, Structureprice(code=code,saleday=saleday,price=price,size=size))
            num +=1

        db.session.bulk_save_objects(xxblue_total)

    db.session.commit()

    return ('찾은값:{} DB에 저장한값:{}'.format(tablenum,num))

@bp.route('/test/')
def test22():
    #shoes = Shoesmodel.query.filter(Shoesmodel.code == 'CU6015-700').first()
    #ssssss = Structureprice.query.filter(Structureprice.code.like('CT8480-001')).order_by(Structureprice.saleday.desc()).first()

    return render_template('shoes/test2.html')

pybo/views/question_views.py
from datetime import datetime
from sqlalchemy import func
from flask import Blueprint, render_template, url_for,request,g,flash
from werkzeug.utils import redirect
from pybo.views.auth_views import login_required
from .. import db
from pybo.models import Question, Answer, User,question_voter
from ..forms import QuestionForm,AnswerForm

bp = Blueprint('question',__name__,url_prefix='/question')

@bp.route('/list/')
def _list():
    # 입력 파라미터
    page = request.args.get('page',type=int,default=1) #페이지
    kw = request.args.get('kw', type=str, default='')
    so = request.args.get('so', type=str, default='recent')

    # 정렬
    if so == 'recommend':
        sub_query = db.session.query(question_voter.c.question_id, func.count('*').label('num_voter')) \
            .group_by(question_voter.c.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_voter.desc(), Question.create_date.desc())
    elif so == 'popular':
        sub_query = db.session.query(Answer.question_id, func.count('*').label('num_answer')) \
            .group_by(Answer.question_id).subquery()
        question_list = Question.query \
            .outerjoin(sub_query, Question.id == sub_query.c.question_id) \
            .order_by(sub_query.c.num_answer.desc(), Question.create_date.desc())
    else:  # recent
        question_list = Question.query.order_by(Question.create_date.desc())

    # 조회
    question_list = Question.query.order_by(Question.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |  # 질문제목
                    Question.content.ilike(search) |  # 질문내용
                    User.username.ilike(search) |  # 질문작성자
                    sub_query.c.content.ilike(search) |  # 답변내용
                    sub_query.c.username.ilike(search)  # 답변작성자
                    ) \
            .distinct()

    # 페이징
    question_list = question_list.paginate(page, per_page=10)

    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html',question = question,form=form)

@bp.route('/create/', methods=('GET','POST'))
@login_required
def create():
    form = QuestionForm()
    #                              form.validate_on_submit() 데이터 정합성체크
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()

        return redirect(url_for('main.index'))

    return render_template('question/question_form.html',form=form)

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)


@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/views/shoes_views.py
from flask import Blueprint, url_for, request, render_template,flash
import os
from werkzeug.utils import redirect,secure_filename
from werkzeug.datastructures import CombinedMultiDict
from pybo.templates.modules.crawl_target import Make_driver
from .. import db
from pybo.models import Shoes,Shoesmodel,Structureprice
from ..forms import SearchShoes,ShoesModelCreateForm
from pybo.views.auth_views import login_required
from pybo.templates.modules.initclass import *
from sqlalchemy import func,nullslast,select
import urllib
import urllib.request
import time

from multiprocessing import Process

bp = Blueprint('shoes',__name__,url_prefix='/shoes')

@bp.route('/main/')
def main():
    #modelprice = Structureprice.query.group_by(Structureprice.code).all()
    modelprice = Structureprice.query.all()
    marketprice = Shoes.query.all()
    model = Shoesmodel.query.all()
    brands = Shoesmodel.query.group_by(Shoesmodel.brand)



    return render_template('shoes/shoes_main.html',modelprice=modelprice,marketprice=marketprice,model=model,brands=brands)


@bp.route('/search/',methods=('GET','POST'))
def search():

    form = SearchShoes()

    if request.method == 'POST' and form.validate_on_submit():

        query_txt = form.content.data
        size = form.size.data
        quantity = form.quantity.data

        howmany=process(query_txt,size,quantity)
        flash(howmany)
        return redirect(url_for('shoes._list'))
    else:
        return render_template('shoes/shoes_search.html',form=form)

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    so = request.args.get('so',type=str, default='recent')


    #정렬
    if so == 'expensive':
        shoes_list = Shoes.query.order_by(Shoes.price.desc())
    elif so =='popular':
        shoes_list = Shoes.query.order_by(Shoes.size.desc())
    else : #최신수
        shoes_list = Shoes.query.order_by(Shoes.id.desc())

    #검색
    if kw:
        search = '%%{}%%'.format(kw)
        if so == 'expensive':
            shoes_list = Shoes.query.filter(Shoes.title.ilike(search) | Shoes.search_query.ilike(search)).order_by(Shoes.price.desc())
        elif so == 'popular':
            shoes_list = Shoes.query.filter(Shoes.title.ilike(search) | Shoes.search_query.ilike(search)).order_by(Shoes.size.desc())
        else:  # 최신수
            shoes_list = Shoes.query.filter(Shoes.title.ilike(search) | Shoes.search_query.ilike(search)).order_by(Shoes.id.desc())


    shoes_list = shoes_list.paginate(page, per_page=10)

    return render_template('shoes/shoes_list.html', shoes_list=shoes_list,page=page,kw=kw,so=so)


@bp.route('/detail/<int:shoes_id>/')
@login_required
def detail(shoes_id):
    shoes = Shoes.query.get_or_404(shoes_id)

    return render_template('shoes/shoes_detail.html',shoes=shoes)

def process(query_txt,size,quantity):
    total_list=[]
    # FOOTSELL CRAWLING
    fs = Foostsell(query_txt,size,quantity)
    fs.start()
    fs.search()
    fs_soup = fs.soup_make()
    fs_obj,count = fs.parser(fs_soup)
    fs.driver.quit()
    num =0
    #zip(title, condition, size, price, seller, uploadtime, uri, img)
    for title, condition, size, price, seller, uploadtime, uri, img in fs_obj:
        fs.img_save(img,img[59:])
        total_list.insert(0, Shoes(title=title, condition=condition, size=size, price=price,
                            seller=seller, upload_date=uploadtime,
                            uri=uri, search_query=query_txt, img=img))
        num +=1

    db.session.bulk_save_objects(total_list)
    db.session.commit()

    return ('찾은값:{} DB에 저장한값:{}'.format(count,num))

pybo/templates/shoes/amount_model.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
     <div class="row justify-content-between my-3">
          <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so=='recent' %}selected{% endif %}>최신순</option>
                <option value="expensive" {% if so=='expensive' %}selected{% endif %}>가격순</option>
                <option value="popular" {% if so=='popular' %}selected{% endif %}>사이즈순</option>
            </select>
        </div>

    </div>
    <table class="table">

        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>사이즈</th>
            <th>가격</th>
            <th>거래일시</th>
        </tr>
        </thead>
        <tbody {% if not g.user %}hidden {% endif %}>
        {% if model_list %}
        {% for model in model_list.items %}

        <tr>
            <td>{{ model_list.total - ((model_list.page-1) * model_list.per_page) - loop.index0 }}</td>
            <td>{{model.size}}</td>
            <td>{{model.price |price}}</td>
            <td>{{model.saleday|datetime}}</td>
        </tr>
        {% endfor %}

        {% else %}
        <tr>
            <td colspan="3">데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    {% if not g.user %}
    <div class="jumbotron">
    <h1 class="text-center">로그인후 이용부탁드립니다.</h1>
  </div>
    {% endif %}
    <ul class="pagination justify-content-center thead-dark">
        <!-- 이전페이지 -->
        {% if model_list.has_prev %}
        <li class="page-item ">
            <a class="page-link" data-page="{{ model_list.prev_num }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in model_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != model_list.page %}
                <li class="page-item ">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if model_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ model_list.next_num }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
<!--    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>-->
</div>
<form id="searchForm" method="get" action="{{ url_for('model._list',code=code) }}">
    <input type="hidden" id="code" name="code" value="{{ code }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script%}
<script type='text/javascript'>



$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));

        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

pybo/templates/shoes/main.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3 center">
    <div class="py-5 text-center">
        <h3>신발검색페이지</h3>
        <p>
        </p>
    </div>

    <div class="jumbotron text-center ">
        <form method="post" class="post-form my-2">
            {{ form.csrf_token }}
        {% include "form_errors.html" %}


            <div class="form-group">
                <label class="col-md-3" for="size">사이즈를 선택하세요 : </label>
                <select class="col-md-2 custom-select custom-select-sm" name="size" id="size">
                    {% for item in form.size %}
                    <option value={{item.data}}>{{item.label}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label class="col-md-3" for="content">검색하실 신발을 입력하세요 : </label>
                <input class="col-md-2" type="text" name="content" id="content" value="{{ form.content.data or ''}}">
            </div>
            <div class="form-group">
                <label class="col-md-3" for="quantity">건수를 입력하세요 : </label>
                <input class="col-md-2" type=number name="quantity" id="quantity" value="{{ form.quantity.data or ''}}">
            </div>


            <br>
            <button type="submit"{% if not g.user %}disabled {% endif %} class="col-md-2 btn btn-secondary">{% if not g.user %}로그인후사용{% else %}검색하기{% endif %}</button>
            <button type="reset" class="col-md-2 btn btn-secondary">초기화</button>
        </form>
    </div>
</div>

{% endblock %}


{% block script%}
{% endblock %}

pybo/templates/shoes/shoes_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
     <div class="row justify-content-between my-3">
          <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so=='recent' %}selected{% endif %}>최신순</option>
                <option value="expensive" {% if so=='expensive' %}selected{% endif %}>가격순</option>
                <option value="popular" {% if so=='popular' %}selected{% endif %}>사이즈순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" onkeyup="enterkey();" value="{{ kw or '' }} ">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">

        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>사이즈</th>
            <th>상태</th>
            <th style="width:50%">제목</th>
            <th>가격</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody {% if not g.user %}hidden {% endif %}>
        {% if shoes_list %}
        {% for shoes in shoes_list.items %}
        <tr>
            <td>{{ shoes_list.total - ((shoes_list.page-1) * shoes_list.per_page) - loop.index0 }}</td>
            <td>{{shoes.size}}</td>
            <td>{{shoes.condition}}</td>
            <td><a href="{{url_for('shoes.detail',shoes_id=shoes.id)}}">{{shoes.title}}</a></td>
            <td>{{shoes.price |price}}</td>
            <td>{{shoes.upload_date|datetime}}</td>
        </tr>
        {% endfor %}

        {% else %}
        <tr>
            <td colspan="3">데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    {% if not g.user %}
    <div class="jumbotron">
    <h1 class="text-center">로그인후 이용부탁드립니다.</h1>
  </div>
    {% endif %}
    <ul class="pagination justify-content-center thead-dark">
        <!-- 이전페이지 -->
        {% if shoes_list.has_prev %}
        <li class="page-item ">
            <a class="page-link" data-page="{{ shoes_list.prev_num }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in shoes_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != shoes_list.page %}
                <li class="page-item ">
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if shoes_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ shoes_list.next_num }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
<!--    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>-->
</div>
<form id="searchForm" method="get" action="{{ url_for('shoes._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script%}
<script type='text/javascript'>
function enterkey() {
        if (window.event.keyCode == 13) {
             // 엔터키가 눌렸을 때 실행할 내용
             btn_search.click();
        }
}


$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

pybo/templates/shoes/shoes_main.html
{% extends 'new_base.html' %}

{% block style %}
.flip-card {

  width: 200px;
  height: 200px;
  perspective: 1000px;
}

.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.6s;
  transform-style: preserve-3d;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}

.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
}

.flip-card-front {

  color: black;
}

.flip-card-back {

  color: white;
  transform: rotateY(180deg);
  justify-content: center;
  align-items: center;
  display: flex;
}
.grid-container{
  display: grid;
  grid-column-gap: 10px;
  grid-template-columns: auto auto auto auto auto;
  padding: 20px;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  text-align: center;

}
.brand-link:hover{

    color:white;
}
h2 {
  color: white;
  text-shadow: 2px 2px 4px #000000;
}

h3 {
  color: white;
  text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;
}
.content-box {
    padding :20px;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}
.content-box-item {
    padding :10px;
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    margin-bottom:10px;
}
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}
.column {
  float: left;
  width: 20%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}


{% endblock %}



{% block content %}



<div class="w3-main w3-content w3-padding" style="max-width:1500px;margin-top:100px">
    <div class="grid-container w3-center" id="brand">
    {%for i in model | groupby('brand')%}
        <div class="grid-item">
        <div class="flip-card">
          <div class="flip-card-inner">
            <div class="flip-card-front">
              <img src="{{url_for('static',filename='brand/{}.png'.format(i[0]))}}" alt="i[0]" style="width:100%">
            </div>
            <div class=" flip-card-back" style="background-color:
                    {% if i[0] =='nike'%}#cb2d3e;{%endif%}
                    {% if i[0] =='converse'%}#fc4a1a;{%endif%}
                    {% if i[0] =='adidas'%}#6A82FB;{%endif%}
                    {% if i[0] =='newbalance'%}#bdc3c7;{%endif%}
                    {% if i[0] =='jordan'%}#DECBA4;{%endif%}">
              <a class="brand-link" href="{{url_for('model.view')}}" style="text-decoration:none; color:white;"><h2>{{i[0]}} : {{i[1] |length}}</h2></a>
            </div>
          </div>
        </div>
    </div>
    {% endfor %}
</div>

    <p>

    <div class='content-box'>
        <div class="content-box-item">
            <h2>시장데이터총양</h2>
            <a  style="text-decoration:none;" href="{{url_for('shoes._list')}}"><h3 style="display:inline">{{marketprice| length}}건</h3></a>
        </div>


<div class="content-box-item">
<h2>거래량이 많은 모델 TOP 5</h2>
    <div class="row">
<!--        내림차순 적용해야함-->
    {% for i in (modelprice | groupby('code'))[:5]%}

        {% for k in model %}
            {%if k.code == i[0]%}
            <div class="column">
                <div class="card">
                    <div style="height:100px; display:inline; padding-top:30px"><a style="text-decoration:none" href="{{url_for('model._list',code=k.code)}}">
                        <h3>{{i[1] |length}}건</h3></a>
                        <span class="font-weight-bold bg-danger text-white">프리미엄↑ : {{((i[1]|sum(attribute='price') // i[1] |length ) - k.retail_price) | price}}</span>
                    </div>
                    <img src="{{url_for('static',filename='crawling_data/model/{}'.format(k.img) )}}" style="max-height:200px;">
                </div>
            </div>
            {% endif %}
        {% endfor %}
    {% endfor%}
        </div>
</div>






{% for i in modelprice | groupby('code') %}
    {% for k in model %}
        {%if k.code == i[0]%}
            {{k.subname}}<br>
            프리미엄↑ :{{((i[1]|sum(attribute='price') // i[1] |length ) - k.retail_price) | price}}<br>
        {% endif %}
    {% endfor %}
        {% for i in i[1]|groupby('size') %}
        size : {{i[0]}} {{i[1] |count}}<br>
        {% endfor %}
코드번호 : {{i[0]}}<br>
거래수 : {{i[1] |length}}<br>
평균가격 : {{ (i[1]|sum(attribute='price') // i[1] |length ) | price}}<br><br>

{% endfor %}

        </div>
{% endblock %}

pybo/templates/shoes/test.html
{% extends 'base.html' %}
{% block content %}
{{model.hashtag}}
{{model}}

{% endblock %}