pybo/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request,session,g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm,UserLoginForm
from pybo.models import User
import functools

bp = Blueprint('auth',__name__,url_prefix='/auth')

@bp.route('/signup',methods=('GET','POST'))
def signup():
    form = UserCreateForm()
    if request.method =='POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        email = User.query.filter_by(email=form.email.data).first()
        if not user and not email:
            user = User(username=form.username.data,
                        password = generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()

            return redirect(url_for('main.index'))
        else:
            if user :
                flash('이미 존재하는 사용자입니다.')
            else:
                flash('이미 사용중인 이메일입니다.')
    return render_template('auth/signup.html',form=form)

@bp.route('/login/',methods=('GET','POST'))
def login():
    form = UserLoginForm()
    if request.method =='POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password,form.password.data):
            error = '비밀번호가 올바르지 않습니다.'
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html',form=form)



@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)




@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

pybo/views/main_view.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect

bp = Blueprint('main',__name__,url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'hello, pybo!'

@bp.route('/')
def index():
    return redirect(url_for('shoes.main'))

pybo/views/model_views.py
from flask import Blueprint, url_for, request, render_template,flash
import os
from werkzeug.utils import redirect,secure_filename
from werkzeug.datastructures import CombinedMultiDict
from pybo.templates.modules.initclass import *
from .. import db
from pybo.models import Shoes,Shoesmodel,Structureprice
from ..forms import SearchShoes,ShoesModelCreateForm
from pybo.views.auth_views import login_required
from sqlalchemy import func,nullslast,select
import urllib
import urllib.request
import time

from multiprocessing import Process

bp = Blueprint('model',__name__,url_prefix='/model')


@bp.route('/list/<code>')
def _list(code):
    page = request.args.get('page', type=int, default=1)
    so = request.args.get('so',type=str, default='recent')
    code=code


    #정렬
    if so == 'expensive':
        model_list = Structureprice.query.filter(Structureprice.code.ilike(code)).order_by(Structureprice.price.desc())
    elif so =='popular':
        model_list = Structureprice.query.filter(Structureprice.code.ilike(code)).order_by(Structureprice.size.desc())
    else : #최신수
        model_list = Structureprice.query.filter(Structureprice.code.ilike(code)).order_by(Structureprice.saleday.desc())


    model_list = model_list.paginate(page, per_page=10)

    return render_template('shoes/amount_model.html', model_list=model_list,page=page,so=so,code=code)

@bp.route('/create/', methods=['GET', 'POST'])
def create():
    form = ShoesModelCreateForm()
    #form = ShoesModelCreateForm(CombinedMultiDict((request.files, request.form)))
    loading = url_for('static',filename='elephant.gif')

    if request.method == 'POST' and form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        brand = form.brand.data
        code = form.code.data
        color = form.colorway.data
        releasedate = form.releasedate.data
        uri=form.uri.data
        img = form.img.data

        rrrr = [name,price,brand,code,color,releasedate,img,uri]

        # 파일저장
        if img == None:
            filename = secure_filename(name)+'.jpg'
            img_path = os.path.join(
                os.getcwd(), r'pybo\static\crawling_data\model', filename)
            #urlretrieve(다운이미지경로,저장위치및이름)
            urllib.request.urlretrieve(uri, img_path)

        else:
            filename = secure_filename(img.filename)
            if name in filename :
                pass
            else:
                filename = secure_filename(name)+'.jpg'
            img.save(os.path.join(
                os.getcwd(), r'pybo\static\crawling_data\model', filename))

        model = Shoesmodel(code=code, img=filename, brand=brand,release_date=releasedate,name=name,colorway=color,retail_price=price)
        db.session.add(model)
        db.session.commit()
        howmany = process(code)

        flash(howmany)

        return redirect(url_for('model.view'))



    else:
        return render_template('shoes/shoes_model_create.html',form=form,loading=loading)




@bp.route('/view/')
def view():

    form = ShoesModelCreateForm()
    forms = form.brand.choices

    items = Shoesmodel.query.order_by(Shoesmodel.release_date.desc())
    return render_template('shoes/shoes_model_list.html',forms=forms,items=items)

def process(code):
    xxblue_total = []
    xb = Xxblue(code)
    xb.start()
    title,img_name = xb.search()
    tablenum = xb.element_generate()
    xb_obj = xb.parser()
    xb.driver.quit()


    # 모델 서브네임이없을 경우 추가한다.
    shoesmodel = Shoesmodel.query.filter(Shoesmodel.code ==code).first()
    if shoesmodel.subname == None:
        shoesmodel.subname = title

    num = 0
    # 중복값 비교
    comparison = Structureprice.query.filter(Structureprice.code.like(code)).order_by(Structureprice.id.desc()).first()

    if '없음' in xb_obj[0][0]:
        pass
    else:
        for i in xb_obj:

            size = i[0]
            price = int(i[1].replace(',', '').replace('원', ''))
            saleday = datetime.strptime(i[2], '%Y.%m.%d')
            # comparison 기존데이터 유무
            if comparison != None :
                if comparison.code == code and comparison.saleday ==saleday and comparison.price == price :
                    break
                else:
                    pass
            else : pass
            xxblue_total.insert(0, Structureprice(code=code,saleday=saleday,price=price,size=size))
            num +=1

        db.session.bulk_save_objects(xxblue_total)

    db.session.commit()

    return ('찾은값:{} DB에 저장한값:{}'.format(tablenum,num))

@bp.route('/test/')
def test22():
    #shoes = Shoesmodel.query.filter(Shoesmodel.code == 'CU6015-700').first()
    #ssssss = Structureprice.query.filter(Structureprice.code.like('CT8480-001')).order_by(Structureprice.saleday.desc()).first()

    return render_template('shoes/test2.html')

pybo/views/shoes_views.py
from flask import Blueprint, url_for, request, render_template,flash
import os
from werkzeug.utils import redirect,secure_filename
from werkzeug.datastructures import CombinedMultiDict
from pybo.templates.modules.crawl_target import Make_driver
from .. import db
from pybo.models import Shoes,Shoesmodel,Structureprice
from ..forms import SearchShoes,ShoesModelCreateForm
from pybo.views.auth_views import login_required
from pybo.templates.modules.initclass import *
from sqlalchemy import func,nullslast,select
import urllib
import urllib.request
import time

from multiprocessing import Process

bp = Blueprint('shoes',__name__,url_prefix='/shoes')

@bp.route('/main/')
def main():
    #modelprice = Structureprice.query.group_by(Structureprice.code).all()
    modelprice = Structureprice.query.all()
    marketprice = Shoes.query.all()
    model = Shoesmodel.query.all()
    brands = Shoesmodel.query.group_by(Shoesmodel.brand)



    return render_template('shoes/shoes_main.html',modelprice=modelprice,marketprice=marketprice,model=model,brands=brands)


@bp.route('/search/',methods=('GET','POST'))
def search():

    form = SearchShoes()

    if request.method == 'POST' and form.validate_on_submit():

        query_txt = form.content.data
        size = form.size.data
        quantity = form.quantity.data

        howmany=process(query_txt,size,quantity)
        flash(howmany)
        return redirect(url_for('shoes._list'))
    else:
        return render_template('shoes/shoes_search.html',form=form)

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    so = request.args.get('so',type=str, default='recent')


    #정렬
    if so == 'expensive':
        shoes_list = Shoes.query.order_by(Shoes.price.desc())
    elif so =='popular':
        shoes_list = Shoes.query.order_by(Shoes.size.desc())
    else : #최신수
        shoes_list = Shoes.query.order_by(Shoes.id.desc())

    #검색
    if kw:
        search = '%%{}%%'.format(kw)
        if so == 'expensive':
            shoes_list = Shoes.query.filter(Shoes.title.ilike(search) | Shoes.search_query.ilike(search)).order_by(Shoes.price.desc())
        elif so == 'popular':
            shoes_list = Shoes.query.filter(Shoes.title.ilike(search) | Shoes.search_query.ilike(search)).order_by(Shoes.size.desc())
        else:  # 최신수
            shoes_list = Shoes.query.filter(Shoes.title.ilike(search) | Shoes.search_query.ilike(search)).order_by(Shoes.id.desc())


    shoes_list = shoes_list.paginate(page, per_page=10)

    return render_template('shoes/shoes_list.html', shoes_list=shoes_list,page=page,kw=kw,so=so)


@bp.route('/detail/<int:shoes_id>/')
@login_required
def detail(shoes_id):
    shoes = Shoes.query.get_or_404(shoes_id)

    return render_template('shoes/shoes_detail.html',shoes=shoes)

def process(query_txt,size,quantity):
    total_list=[]
    # FOOTSELL CRAWLING
    fs = Foostsell(query_txt,size,quantity)
    fs.start()
    fs.search()
    fs_soup = fs.soup_make()
    fs_obj,count = fs.parser(fs_soup)
    fs.driver.quit()
    num =0
    #zip(title, condition, size, price, seller, uploadtime, uri, img)
    for title, condition, size, price, seller, uploadtime, uri, img in fs_obj:
        fs.img_save(img,img[59:])
        total_list.insert(0, Shoes(title=title, condition=condition, size=size, price=price,
                            seller=seller, upload_date=uploadtime,
                            uri=uri, search_query=query_txt, img=img))
        num +=1

    db.session.bulk_save_objects(total_list)
    db.session.commit()

    return ('찾은값:{} DB에 저장한값:{}'.format(count,num))

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='style.css' ) }}">
    <title>hello, pybo</title>
    <style>
    {% block style %}
    {% endblock %}
    </style>
</head>
<body>
{% include 'navbar.html'%}
{% block content %}
{% endblock %}
<script src="{{url_for('static',filename='jquery-3.5.1.min.js')}}"></script>
<script src="{{url_for('static',filename='bootstrap.min.js')}}"></script>

{% block script%}
{% endblock %}
</body>
</html>

pybo/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors)}}
</div>
{% endfor %}

{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">DONGGI</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">

        <ul class="navbar-nav">

            {% if g.user %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
            </li>
            {% else %}
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
            </li>
            {% endif %}

            {% if g.user.username == '1234' %}
            <li class="nav-item">
                 <a class="nav-link" href="{{url_for('shoes.search')}}">신발시장 크롤링</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link" href="{{url_for('model.create')}}">신발모델 생성</a>
            </li>

            {% endif %}
            <li class="nav-item">
                 <a class="nav-link" href="{{url_for('model.view')}}">모델 조회</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link" href="{{url_for('shoes._list')}}">시장시세조회</a>
            </li>
        </ul>
    </div>
</nav>

pybo/templates/new_base.html
<!DOCTYPE html>
<html>
<title>Donggi</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<link rel="stylesheet" href="{{ url_for('static',filename='bootstrap.min.css')}}">
<link rel="stylesheet" href="{{ url_for('static',filename='style.css' ) }}">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
{% block style %}
{% endblock %}
</style>

<body>
{% include 'navbar.html'%}
{% block content %}
{% endblock %}

<script src="{{url_for('static',filename='jquery-3.5.1.min.js')}}"></script>
<script src="{{url_for('static',filename='bootstrap.min.js')}}"></script>

{% block script%}
{% endblock %}
</body>
</html>

pybo/templates/success.html
{% with messages = get_flashed_messages() %}
	{% if messages %}
	{% for message in messages %}
	<!--{{ message }}-->
<script>
		alert('{{message}}')   //이 부분이 중요
	</script>
	{% endfor %}
	{% endif %}
{% endwith %}